### ISSUE TITLE
Event storming realização do pedido e pagamento

### ISSUE THREAD

**Issue by GabrielUmbelino** [GabrielUmbelino/fiap-pos-tech-challenge#12]

**Comment by bzanella** [comment]
LINK PARA BOARD DO MIRO 👇

https://miro.com/welcomeonboard/aU8zSUZWODdGZ0NlNGRUQUZJTlM0WmNkUTY0cXF4WVg2eWpTZEhwZGhRYXNJcXM2WHcwN0lnV0lNekhRUUxvZXwzMDc0NDU3MzYyNzY4NzA5ODcyfDI=?share_link_id=173165922485

**Comment by bzanella** [comment]
Qualquer ideia/sugestão podem copiar os itens q ja estão lá e inserir as modificações
